In [2]:
import numpy as np
from builtins import print
#apppending normal vector
L = [1, 2, 3]
A = np.array([1, 2, 3])
for e in L:
    print(e)


1
2
3


In [3]:
L.append(4)
print(L)
L = L+[5]
L



[1, 2, 3, 4]


[1, 2, 3, 4, 5]

In [10]:
#to sum element in vector
L2 = []
for e in L:
    L2.append(e+e)
L2


[2, 4, 6, 8, 10]

In [11]:
#to sum numpy array :
A+A



array([2, 4, 6])

In [7]:
2*A

array([2, 4, 6])

In [9]:
2*L

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5]

In [12]:
#to do  square 
for e in L : 
    L2.append(e*e)
L2

[2, 4, 6, 8, 10, 1, 4, 9, 16, 25]

In [13]:
#square vetor in numpy 
A*A

array([1, 4, 9])

In [15]:
#racine carré
np.sqrt(A)

array([ 1.        ,  1.41421356,  1.73205081])

In [16]:
#log
np.log(A)

array([ 0.        ,  0.69314718,  1.09861229])

In [17]:
#exponential 
np.exp(A)

array([  2.71828183,   7.3890561 ,  20.08553692])