In [1]:
import numpy as np
#use list of list 
M = np.array([[1,2],[3,4]])
L = [[1,2],[3,4]]
#python way 
L[0]

[1, 2]

In [5]:
L[0][0]

1

In [7]:
#numpy
M[0,0]

1

In [9]:
#not possible  python 
L[0,0]

TypeError: list indices must be integers or slices, not tuple

In [10]:
#do it proper numpy way
M2 = np.matrix([[1,2],[3,4]])

In [11]:
M2

matrix([[1, 2],
        [3, 4]])

In [14]:
#we can cast from matrix to array  
A = np.array(M2)
A

array([[1, 2],
       [3, 4]])

In [36]:
#transpse
B = A.T
B

array([[1, 3],
       [2, 4]])

In [37]:
B.transpose()

array([[1, 2],
       [3, 4]])

In [39]:
#initiate an array with dimentions 
Z=np.array(10)
Z   

array(10)

In [40]:
X= np.zeros(10)
X

array([ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.])

In [42]:
Z = np.zeros((10,10))
Z

array([[ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.]])

In [43]:
O = np.ones((10,10))
O

array([[ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.]])

In [46]:
R = np.random.random((10,10))
R

array([[ 0.71108242,  0.73466408,  0.18686557,  0.40170543,  0.9497457 ,
         0.86924604,  0.7798938 ,  0.42772929,  0.32069523,  0.31598477],
       [ 0.01980719,  0.48142917,  0.40268253,  0.04050179,  0.75868204,
         0.04283494,  0.00970955,  0.02385045,  0.83112891,  0.88627181],
       [ 0.22422787,  0.7964493 ,  0.79795381,  0.9340276 ,  0.08943557,
         0.33661864,  0.10091239,  0.02133902,  0.99033585,  0.81358388],
       [ 0.53138005,  0.16310814,  0.62577381,  0.21732397,  0.97133104,
         0.9095629 ,  0.98428042,  0.05175073,  0.85937926,  0.74488229],
       [ 0.4053387 ,  0.36761572,  0.82710725,  0.31630487,  0.41703455,
         0.80105641,  0.24858055,  0.15069358,  0.99891771,  0.02337136],
       [ 0.5205826 ,  0.82577593,  0.32591489,  0.89872232,  0.28994962,
         0.77945841,  0.34999382,  0.88080074,  0.71006044,  0.89283399],
       [ 0.66413478,  0.03714031,  0.24486892,  0.02048787,  0.69309516,
         0.45738831,  0.82976964,  0.2367072 

In [47]:
#gaussian  distrub
G = np.random.randn(10,10)
G

array([[ 1.30961032,  0.30150114, -0.47430539, -0.86803185,  0.34213205,
        -0.1602205 , -0.68261866,  1.21399851, -3.05435932, -0.10501978],
       [-0.03328133,  0.32842273, -1.23732081,  1.55698728,  0.3906004 ,
         0.11742851,  1.09315004,  2.48841931, -0.76364079,  0.05144176],
       [-0.32931541,  0.25400642,  1.13504599, -2.03439934,  0.22464706,
         0.91041278,  1.10141949, -0.53274939, -1.84488682,  2.09053667],
       [-1.69186771,  0.80665657,  0.43386671, -0.01973859, -1.25964465,
         0.76024174,  0.22242408, -0.89110306, -0.14886625, -1.28828532],
       [ 1.10209881,  0.11834977, -0.37836139, -0.47756989,  0.77198056,
        -0.06261803,  2.20124073,  1.89424124, -0.62224803,  1.03497149],
       [ 0.37804725, -0.265647  ,  0.13738289,  1.0770705 ,  0.09305553,
        -0.62908463, -0.67054637, -0.04012464, -0.07126794,  2.09832929],
       [-1.442813  , -0.7817422 , -2.17901544,  0.33853418,  0.75102663,
        -0.03043002,  1.34639653, -0.01473717

In [49]:
#statistic functions :
G.mean()

0.1041609479271596

In [50]:
G.var()

1.0343565351587332

In [52]:
# matrix products : produit matriciel
# in numpy "*" means element by element multiplication && ".dot()" means matrix multiplication
Cmp = G.dot(O)
Cmp

array([[-2.17731346, -2.17731346, -2.17731346, -2.17731346, -2.17731346,
        -2.17731346, -2.17731346, -2.17731346, -2.17731346, -2.17731346],
       [ 3.99220708,  3.99220708,  3.99220708,  3.99220708,  3.99220708,
         3.99220708,  3.99220708,  3.99220708,  3.99220708,  3.99220708],
       [ 0.97471746,  0.97471746,  0.97471746,  0.97471746,  0.97471746,
         0.97471746,  0.97471746,  0.97471746,  0.97471746,  0.97471746],
       [-3.07631649, -3.07631649, -3.07631649, -3.07631649, -3.07631649,
        -3.07631649, -3.07631649, -3.07631649, -3.07631649, -3.07631649],
       [ 5.58208527,  5.58208527,  5.58208527,  5.58208527,  5.58208527,
         5.58208527,  5.58208527,  5.58208527,  5.58208527,  5.58208527],
       [ 2.10721488,  2.10721488,  2.10721488,  2.10721488,  2.10721488,
         2.10721488,  2.10721488,  2.10721488,  2.10721488,  2.10721488],
       [-1.20606738, -1.20606738, -1.20606738, -1.20606738, -1.20606738,
        -1.20606738, -1.20606738, -1.20606738

In [53]:
Cem = G*O
Cem

array([[ 1.30961032,  0.30150114, -0.47430539, -0.86803185,  0.34213205,
        -0.1602205 , -0.68261866,  1.21399851, -3.05435932, -0.10501978],
       [-0.03328133,  0.32842273, -1.23732081,  1.55698728,  0.3906004 ,
         0.11742851,  1.09315004,  2.48841931, -0.76364079,  0.05144176],
       [-0.32931541,  0.25400642,  1.13504599, -2.03439934,  0.22464706,
         0.91041278,  1.10141949, -0.53274939, -1.84488682,  2.09053667],
       [-1.69186771,  0.80665657,  0.43386671, -0.01973859, -1.25964465,
         0.76024174,  0.22242408, -0.89110306, -0.14886625, -1.28828532],
       [ 1.10209881,  0.11834977, -0.37836139, -0.47756989,  0.77198056,
        -0.06261803,  2.20124073,  1.89424124, -0.62224803,  1.03497149],
       [ 0.37804725, -0.265647  ,  0.13738289,  1.0770705 ,  0.09305553,
        -0.62908463, -0.67054637, -0.04012464, -0.07126794,  2.09832929],
       [-1.442813  , -0.7817422 , -2.17901544,  0.33853418,  0.75102663,
        -0.03043002,  1.34639653, -0.01473717

In [54]:
#matrix operations  
#inverse :
A = np.array([[1,2],[3,4]])
Ainv = np.linalg.inv(A)
Ainv

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [55]:
Ainv.dot(A)

array([[  1.00000000e+00,   0.00000000e+00],
       [  1.11022302e-16,   1.00000000e+00]])

In [56]:
A.dot(Ainv)

array([[  1.00000000e+00,   0.00000000e+00],
       [  8.88178420e-16,   1.00000000e+00]])

In [57]:
#matrix determin
np.linalg.det(A)

-2.0000000000000004

In [58]:
#matrix diagonal
np.diag(A)

array([1, 4])

In [59]:
#if we want to cerate an  matrix from diag array and the rest is zero
np.diag([1,2,3,4,5,6,7,8,9])

array([[1, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 2, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 3, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 4, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 5, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 6, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 7, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 8, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 9]])

In [60]:
#outer/inner product
v1= np.array([1,2])
v2 = np.array([3,4])
np.outer(v1,v2)

array([[3, 4],
       [6, 8]])

In [61]:
np.inner(v1,v2)

11

In [62]:
v1.dot(v2)

11

In [64]:
np.trace(O)

10.0

In [65]:
np.diag(O).sum()

10.0

In [73]:
#example to calculate the covariance of a randon gaussian distributiuon with 3 features and 100 sample
X= np.random.randn(100,3)
cov = np.cov(X)
cov.shape


(100, 100)

In [74]:
#it is wrong covariance , should be 3,3
cov = np.cov(X.T)
cov

array([[ 0.79805613, -0.054528  ,  0.08645369],
       [-0.054528  ,  1.11394741,  0.00179683],
       [ 0.08645369,  0.00179683,  1.00012199]])

In [75]:
#EigenValue & EigenVector | valeur propre et vercteur propre
np.linalg.eigh(cov)

(array([ 0.75855101,  1.02895045,  1.12462406]),
 array([[ 0.93128788, -0.30796359, -0.19457986],
        [ 0.14457678, -0.17780938,  0.97338655],
        [-0.33436574, -0.93463482, -0.12106733]]))

In [76]:
#eig may varry order
np.linalg.eig(cov)

(array([ 0.75855101,  1.02895045,  1.12462406]),
 array([[-0.93128788, -0.30796359, -0.19457986],
        [-0.14457678, -0.17780938,  0.97338655],
        [ 0.33436574, -0.93463482, -0.12106733]]))