In [9]:
import numpy as np

#problem ax=b
a = np.array([[1,2],[3,4]])
a

array([[1, 2],
       [3, 4]])

In [10]:
b = np.array([1,2])
b

array([1, 2])

In [11]:
x = np.linalg.inv(A).dot(b)
x

array([ 0. ,  0.5])

In [12]:
#or solve the np function
np.linalg.solve(a,b)

array([ 0. ,  0.5])

In [13]:
# solving a simple equation :
# the admission fee in a fair is 1.5 for child and 4 for adult, the ammount collected is 5050 for 2200
# how many adults and childs attended?
# Nchi + Nadu = 2200 
# 1.5Nchi + 4Nadu =5050
# equation will be [[1,1][1.5,4]].dot([Nchi,Nadu) = (2200,5050)
sol = np.linalg.solve(np.array([[1,1],[1.5,4]]),[2200,5050])
sol

array([ 1500.,   700.])